#!/bin/csh
set arch = intelxeon
set threading = yes
set chunk = 4
set translatei = auto
set fpmp = no
set iinside = no
set nz = 32
set objdir = /home/keirouz/Pearls2_Chapter02_Copy/src_intelxeon_ompyes_CHUNK4_NZ32_FPMPno
  # Enable Intel-specific Xeon cmds
  # add any module commands here
  set path = ( /opt/pgi/linux86-64/16.10/bin /root/perl5/bin /big/hadoop-2.5.0-cdh5.3.0/bin /usr/lib/jvm/jre-1.8.0-openjdk/bin /big/apache-maven-3.3.9/bin /opt/scorep/bin /big/chapel-1.14.0/bin/linux64 /big/tau-2.25.2/x86_64/bin /big/berkeley_upc-2.22.3 /big/Intel/bin/compilers_and_libraries/linux/bin/intel64 /big/Intel/bin/compilers_and_libraries_2017.1.132/linux/mpi/intel64/bin /big/Intel/bin/intelpython27/bin /big/Intel/bin/advisor/bin64 /usr/local/bin /usr/bin /usr/local/sbin /usr/sbin /home/keirouz/.local/bin /home/keirouz/bin /opt/intel/bin )
